version: "3.8"

services:
  db:
    container_name: ${CONTAINER_NAME}
    image: mysql:${MYSQLDB_VERSION}
    restart: always
    ports:
      - "${MYSQLDB_PORT}:${MYSQLDB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "-h", "localhost", "-u", "${MYSQLDB_USER}", "-p${MYSQLDB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://db:${MYSQLDB_PORT}/${MYSQLDB_DATABASE}",
          "spring.datasource.username": "${MYSQLDB_USER}",
          "spring.datasource.password": "${MYSQLDB_PASSWORD}",
          "jwt.expiration": ${JWT_EXPIRATION},
          "jwt.secret": "${JWT_SECRET}"
        }
